//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcom.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KargoBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KargoBilgileri()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int Id { get; set; }
        public string FirmaAdi { get; set; }
        public int Durumu { get; set; }
        public int TeslimatAdresId { get; set; }
        public int KargoTakipNo { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
