//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcom.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int Id { get; set; }
        public int SepetId { get; set; }
        public int IndirimTutari { get; set; }
        public int SatisTutari { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public Nullable<int> SatisDurumu { get; set; }
        public Nullable<int> FaturaAdresId { get; set; }
        public Nullable<int> KargoId { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual KargoBilgileri KargoBilgileri { get; set; }
        public virtual Sepet Sepet { get; set; }
    }
}
