//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcom.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.SepetUrun = new HashSet<SepetUrun>();
            this.UrunKategori = new HashSet<UrunKategori>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKodu { get; set; }
        public Nullable<decimal> Fiyati { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int Durum { get; set; }
        public int Stok { get; set; }
    
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetUrun> SepetUrun { get; set; }
        public virtual UrunOzellikleri UrunOzellikleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunKategori> UrunKategori { get; set; }
    }
}
